# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://andmore.dev/"
DefaultContentLanguage  = "en"
title                   = "AndMore Dev"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = "G-HV164KHRN5"
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "linkedin", "email"]
  hideEmptyStats        = true

  [params.meta]
    description         = "Just another blog about cloud and serverless"
    author              = "Andres Moreno"
    favicon             = true
    svg                 = false
    faviconVersion      = "3"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "AndMore Dev"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Andres Moreno"
    paragraph             = "I'm Andres Moreno, Lead Software Engineer at Tyler Technologies. I focus on serverless techonology in AWS"
    rssIntro              = false
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/logo.jpg"
      shape               = "circle"
      width               = ""
      alt                 = "Andres Moreno Profile Pictrue"

  [params.sidebar]
    about               = ""
    postAmount          = 5
    categories          = false
    categoriesByCount   = false

  [params.footer]
    rssFooter           = false
    socialFooter        = false

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = "main"

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.es]
    LanguageCode        = "es"
    LanguageName        = "Español"
    weight              = 2

[social]
  github                = "andmoredev"
  medium                = "andmoredev"
  linkedin              = "andmoredev"
  twitter               = "andmoredev"
